stages:
  data_ingestion:
    cmd: python3 src/PotatoDisease/pipeline/stage_01_data_ingestion.py
    deps:
      - src/PotatoDisease/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/PlantVillage