stages:
  data_ingestion:
    cmd: python3 src/PotatoDisease/pipeline/stage_01_data_ingestion.py
    deps:
      - src/PotatoDisease/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/PlantVillage

  data_validation:
    cmd: python3 src/PotatoDisease/pipeline/stage_02_data_validation.py
    deps:
      - src/PotatoDisease/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/PlantVillage
    outs:
      - artifacts/data_validation/status.txt
    
  model_training:
    cmd: python3 src/PotatoDisease/pipeline/stage_03_model_training.py 
    deps:
      - src/PotatoDisease/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/PlantVillage
    outs:
      - artifacts/model_training/model.h5