artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: https://drive.google.com/file/d/1XboDAEEC_QsRP5HVVGPEuL27XCmPCiIH/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/PlantVillage
  status: artifacts/data_validation/status.txt


model_training:
  root_dir: artifacts/model_training
  dataset_path: artifacts/data_ingestion/PlantVillage
  model_save: artifacts/model_training/model.h5
